//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunTimeBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTENT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTENT_TYPE()
        {
            this.ANSWERS = new HashSet<ANSWERS>();
        }
    
        public int Id { get; set; }
        public int luis_id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERS> ANSWERS { get; set; }
        public virtual LUIS_TYPE LUIS_TYPE { get; set; }
    }
}
